# Generated by Django 3.0.8 on 2020-07-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0002_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
    ]
