# Generated by Django 3.0.8 on 2020-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0003_auto_20200720_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hands',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
