# Generated by Django 3.0.8 on 2020-07-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0005_auto_20200720_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hands',
            name='num_of_players',
            field=models.IntegerField(choices=[(2, '2'), (3, '3')], verbose_name='Nr of players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='flop_act_amount',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='players',
            name='flop_action',
            field=models.CharField(blank=True, choices=[('R', 'raise'), ('F', 'fold'), ('C', 'call'), ('X', 'check'), ('X/F', 'checkfold'), ('B', 'bet')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='hero',
            field=models.BooleanField(default=False, null=True, verbose_name='Is it hero?'),
        ),
        migrations.AlterField(
            model_name='players',
            name='pre_act_amount',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='players',
            name='pre_action',
            field=models.CharField(blank=True, choices=[('R', 'raise'), ('F', 'fold'), ('C', 'call'), ('C', 'check')], max_length=50, null=True, verbose_name='PreFlop action'),
        ),
    ]
