# Generated by Django 3.0.8 on 2020-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0006_auto_20200721_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='first_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='second_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hands',
            name='num_of_players',
            field=models.IntegerField(choices=[(2, '2'), (3, '3')], default=2, verbose_name='Nr of players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='first_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='flop_action',
            field=models.CharField(blank=True, choices=[('F', 'Fold'), ('X', 'Check'), ('L', 'Limp'), ('C', 'Call'), ('R', 'Raise'), ('X/F', 'Check/Fold'), ('X/C', 'Check/Call'), ('X/R', 'Check/Raise'), ('L/F', 'Limp/Fold'), ('L/C', 'Limp/Call'), ('L/R', 'Limp/Raise'), ('C/F', 'Call/Fold'), ('C/C', 'Call/Call'), ('C/R', 'Call/Raise'), ('R/F', 'Raise/Fold'), ('R/C', 'Raise/Call'), ('R/R', 'Raise/Raise')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='pre_action',
            field=models.CharField(blank=True, choices=[('F', 'Fold'), ('X', 'Check'), ('L', 'Limp'), ('C', 'Call'), ('R', 'Raise'), ('L/F', 'Limp/Fold'), ('L/C', 'Limp/Call'), ('L/R', 'Limp/Raise'), ('C/F', 'Call/Fold'), ('C/C', 'Call/Call'), ('C/R', 'Call/Raise'), ('R/F', 'Raise/Fold'), ('R/C', 'Raise/Call'), ('R/R', 'Raise/Raise')], max_length=50, null=True, verbose_name='PreFlop action'),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=10, null=True),
        ),
    ]
