# Generated by Django 3.0.8 on 2020-07-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0008_auto_20200722_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='hero',
            field=models.CharField(choices=[('H', 'Hero'), ('', 'Villain')], default='Villain', max_length=10, verbose_name='Is it hero?'),
        ),
    ]
