# Generated by Django 3.0.8 on 2020-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0009_auto_20200723_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='hero',
            field=models.CharField(choices=[('H', 'Hero'), ('', 'Villain')], default='', max_length=10, verbose_name='Is it hero?'),
        ),
    ]
