# Generated by Django 3.0.8 on 2020-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0011_auto_20200723_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='first_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='first_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club')], max_length=2, null=True),
        ),
    ]
