# Generated by Django 3.0.8 on 2020-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0014_auto_20200728_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='hands',
            name='turn_card',
            field=models.CharField(choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), (' ', 'x')], default='x', max_length=2),
        ),
        migrations.AddField(
            model_name='hands',
            name='turn_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club'), ('x', 'x')], default='x', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='first_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), (' ', 'x')], default=' ', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='first_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club'), ('x', 'x')], default='x', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='flop_act_amount',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='players',
            name='pre_act_amount',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='players',
            name='river_act_amount',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), (' ', 'x')], default=' ', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club'), ('x', 'x')], default='x', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='turn_act_amount',
            field=models.CharField(blank=True, default='0', max_length=20, verbose_name='Amount'),
        ),
    ]
