# Generated by Django 3.0.8 on 2020-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0015_auto_20200729_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='first_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club'), ('x', 'x')], default='x', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(blank=True, choices=[('UTG', 'Under The Gun'), ('MP', 'Middle Position'), ('CO', 'Cut-off'), ('BTN', 'Button'), ('SB', 'Small Blind'), ('BB', 'Big Blind')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='second_card_suit',
            field=models.CharField(blank=True, choices=[('s', 'Spade'), ('h', 'Heart'), ('d', 'Diamond'), ('c', 'Club'), ('x', 'x')], default='x', max_length=2, null=True),
        ),
    ]
