# Generated by Django 3.0.8 on 2020-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0016_auto_20200729_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hands',
            name='turn_card',
            field=models.CharField(choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('T', 'T'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), (' ', 'x')], default=' ', max_length=2),
        ),
    ]
